// script to add a new entitlement group to the system

response = {};

// check if groupname exists already
getGroup = #entitlement.getEntitlementGroup(web["groupName"]);

if(getGroup == null) do               // group does not exist
    // create group
    try do
        #entitlement.addEntitlementGroup(web["groupName"]);
    end
    catch e do
        response.error = (fromjson(json(e)))["message"];
    end
else do
    response.error = "Group name exists.";
end

println(json(response));
