// script to run a workflow (i.e. create a workorder)

require '///webscript/stringUtil' as stringUtil;

response = {};
parameters = web["parameters"];

uri = "workflow://" + web["workflowPath"];

if parameters == null do
	parameters = {};
else do
	parameters = fromjson(parameters);
end

workorderUri = #decision.createWorkOrder(uri, parameters);

response.workorder = {
	"uri": workorderUri,
	"name": stringUtil.extractName(workorderUri)
};

println(json(response));
