// A script to return information about a specified currency

response = {};

w = (fromjson(widgetParams));
entity = w.entity;
currency = w.key;

info = fromjson(#entity.getEntityDocByKey("//standard/currency", currency));

data = [];
vc = #entity.getViewConfiguration(entity);
for idx = 0 to size(vc) - 1 do
    item = {};
    prop = vc[idx]["name"];
    item[prop] = info[prop];
    data += item;
end

response.data = data;

return(json(response));
