// A script to return a list of all workorders for a specified workflow

require '///webscript/stringUtil' as stringUtil;

response = {};
result = [];
w = fromjson(widgetParams);
wfUri = "workflow://" + w.key;

workorders = #decision.getWorkOrdersByWorkflow(0, wfUri);

for wo in workorders do
    workorder = {};
    workorder.uri = wo;
    workorder.name = stringUtil.extractName(wo);
    result += workorder;
end

response.data = result;

return(json(response));